// @ts-check
// The Receive box and the shared "Board" row (P3a-2, USB serial). One file per unit, same namespace
// pattern: see strings/parts-text.en.mjs for why.
import { registerStrings } from '../core/i18n.mjs';

registerStrings('parts', {
  receiveLabel: 'Receive',
  receiveHint: 'Hands on what a board says over USB (one line per message) or what arrives on the farm’s message bus. JSON flows on as data.',
  receiveFrom: 'From',
  receiveFromHint: 'Where the messages come from: a board plugged into this computer’s USB cable, or a topic on the farm’s message bus (MQTT, WebSocket or OSC, from anything on the network).',
  receiveFrom_serial: 'a board on USB',
  receiveFrom_bus: 'the farm’s message bus',
  receiveTopic: 'Topic',
  receiveTopicHint: 'The topic to listen to on the farm’s message bus. + stands for any one level, # for everything below: lol/# hears every lol/ topic.',
  receiveNoTopic: 'Type a topic, like lol/+/light (+ is any one level, # anything below).',
  receiveNothingBus: 'Nothing on {topic} yet. Is the board or the tool publishing there?',
  receiveNothingNewBus: 'No new message on {topic} since the last run.',
  busErrNoBus: 'This farm has no message bus: its operator turns it on in the farm panel (Plugins).',
  receiveTake: 'Hand on',
  receiveTakeHint: 'The latest message: only the last one to arrive. Every new message: a list of all that arrived since the last run.',
  receiveTake_latest: 'the latest message',
  receiveTake_new: 'every new message since the last run',
  receiveListening: 'Listening to {name}…',
  receiveLast: 'Last line: {line}',
  receiveNothing: 'Nothing from the board yet. Is it plugged in, and sending lines at {baud} baud?',
  receiveNothingNew: 'No new line from the board since the last run.',
  receiveNoBoard: 'Choose the board first.',
  boardChoose: 'Choose the board…',
  boardChooseHint: 'Lists the boards plugged in over USB; you pick one.',
  boardBaud: 'Speed (baud)',
  boardBaudHint: 'How fast the board talks: the number in its sketch’s Serial.begin(…). Both sides must use the same one; 115200 is the usual.',
  boardIs: 'Board: {name}',
  boardNone: 'No board chosen',
  boardErrNoSerial: 'USB serial is not available in this window.',
  boardErrNone: 'No board found. Plug it in with a data cable (some cables only charge), then try again.',
  boardErrCancelled: 'No board chosen.',
  boardErrNotFound: 'The board is not plugged in (or was unplugged).',
  boardErrBusy: 'The board is busy: close the Arduino Serial Monitor, or any other program using it.',
  boardErrLost: 'The board stopped answering (unplugged?).',
});
