// @ts-check
// The Home boxes (docs/HOME_ASSISTANT.md, 2026-10-09): Home reads the devices a person picked, Home command switches
// one. One file per unit, same namespace pattern: see strings/parts-text.en.mjs for why.
import { registerStrings } from '../core/i18n.mjs';

registerStrings('parts', {
  homeLabel: 'Home',
  homeHint: 'Reads the devices and sensors of your Home Assistant that you choose: their state now, a weather’s forecast, a calendar’s events of the next 24 hours, and their history when you ask for it. Reading changes nothing in the home. Link your Home Assistant in Preferences ▸ Home Assistant.',
  homeChoose: 'Choose…',
  homeChooseHint: 'Pick the devices and sensors this box reads, from the list of your home.',
  homeNone: 'No device chosen yet.',
  homeSome: '{n} chosen: {names}',
  homeHours: 'History (hours)',
  homeHoursHint: '0 reads the state now. 1 to 168 also brings each device’s values over that many past hours (at most 240 per device), for a chart: up to 4 devices over a week, 30 over a day. Never where people were.',
  homeSearch: 'Search the home',
  homeDone: 'Done',
  homeListMore: '… and {n} more: type to narrow the list.',
  homeNoMatch: 'Nothing in your home matches.',
  homeRead: 'Read {n} from {home} · {time}',
  homeMissing: 'Not in this home: {ids}',
  homeSaved: 'Saved copy — {why}',
  homeNoDoor: 'This version of the app cannot reach Home Assistant — update LlmOnLan.',
  homeErr_empty: 'Choose the devices to read first (Choose…).',
  homeErr_nolink: 'No Home Assistant is linked. Link yours in Preferences ▸ Home Assistant.',
  homeErr_offline: 'Home Assistant did not answer: {message}',
  homeErr_refused: '{message}',
  homeErr_notHere: 'None of these devices is in your home ({ids}): pick yours with Choose…',

  homeCmdLabel: 'Home command',
  homeCmdIn: 'go',
  homeCmdHint: 'Tells ONE device of your home to do ONE thing you choose here, each time something arrives (what arrives is only the signal to act). A dry run until you arm the outputs in the run bar AND allow home commands in Preferences ▸ Home Assistant. Never unlocks a lock, disarms an alarm, sounds a siren, opens a valve, a door or a garage.',
  homeCmdDevice: 'Device',
  homeCmdNone: 'No device chosen yet.',
  homeCmdIs: '{name} ({id})',
  homeCmdChooseHint: 'Pick the one device this box commands, from your home’s devices.',
  homeCmdAction: 'Action',
  homeCmdActionHint: 'What the device does. Only the actions LlmOnLan allows for this kind of device are listed.',
  homeCmdActionNone: 'Choose a device first',
  homeCmdData: 'With (optional)',
  homeCmdDataHint: 'Extra details for the action, as JSON, like {"brightness_pct": 40}. Only what you type here is sent: what arrives on the arrow is only the signal to act.',
  homeCmdDataBad: '“With” is not JSON: write it like {"brightness_pct": 40}, or leave it empty.',
  homeCmdNoTarget: 'Choose the device and the action first.',
  homeCmdEmpty: 'Nothing arrived: wire something into this box — it is the signal to act.',
  homeCmdDone: 'Done: {what}. It is now {now}.',
  homeCmdDryOutputs: 'Dry run — would do {what}. Arm the outputs in the run bar to send it.',
  homeCmdDryHome: 'Dry run — would do {what}. Allow home commands in Preferences ▸ Home Assistant to send it.',
  homeCmdDryNoHome: 'Dry run — no Home Assistant is linked. It would do {action} on {name}.',
  homeCmdErr_missing: 'The device {id} is not in your home: pick one with Choose…',
  homeCmdErr_readonly: 'A {domain} only reports: it cannot be commanded. Choose a light, a switch, a fan…',
  homeCmdErr_never: 'Never from LlmOnLan: {what}. A person does that in Home Assistant.',
  homeCmdErr_action: 'That action is not allowed on this device. Allowed: {what}.',
  homeCmdErr_tooBig: 'The details are too large for one command.',
  homeCmdErr_notListed: 'This device was not in the list you allowed. Allow home commands again to include it.',
  homeCmdErr_rate: 'Held back: one command a second per device, 30 a minute in all. Slow the graph down (a Timer).',
  homeCmdErr_unconfirmed: 'Sent, not confirmed: {what}. Home Assistant may still be doing it; check the device before running again.',
  homeCmdErr_error: 'Home Assistant: {message}',
  homeCmdTarget: 'Home Assistant → {action} on {name}',
  homeCmdWith: 'with {data}',
});
