// @ts-check
// Strings for the Project panel — LOL Vibe's IDE (ui/project-panel.mjs, docs/IDE_PLAN.md).
import { registerStrings } from '../core/i18n.mjs';

registerStrings('project', {
  label: 'Project',
  emptyTitle: 'Build with the coding agent',
  emptyBody: 'Make a new project, or pick one from the list. Then ask in the chat, for example: "make a three.js page with a rotating cube". The coding agent writes the files in a folder on this computer, thinking with the farm\'s model; nothing is kept on the farm.',
  newPlaceholder: 'New project name',
  create: 'New project',
  other: 'Other project',
  folder: 'Open folder',
  browser: 'Open in browser',
  share: 'Share on the LAN',
  unshare: 'Stop sharing',
  shared: 'Shared on the LAN, read-only: {urls} — anyone on this network can open it. It stops when LlmOnLan closes.',
  sharedNoLan: 'This computer has no network address right now, so there is nothing to share on.',
  keepGoing: 'Keep going until done',
  keepGoingOn: 'Keep going until done: on',
  keepGoingNote: 'On: your next messages start a loop — the agent works round after round (at most {max}) until it has checked the job is done. Each round is a whole reply of the model on the farm. Stop ends it; it switches off when LlmOnLan closes.',
  schedule: 'Schedule…',
  scheduleOn: 'Schedule: on',
  schedKindLabel: 'How often',
  schedEvery: 'Every … minutes',
  schedAt: 'Every day at …',
  schedMinLabel: 'Minutes between runs',
  schedTimeLabel: 'Time of day',
  schedTextLabel: 'The message to send each time',
  schedPlaceholder: 'What the agent should do each time — e.g. "Check the page still works and add today\'s date to log.md"',
  schedStart: 'Start',
  schedStop: 'Stop the schedule',
  schedOff: 'The agent gets this message by itself, in this chat — every {min} minutes at the most, only while LlmOnLan is open, and never while a reply is running. It is forgotten when LlmOnLan closes.',
  schedOn: 'On: next run {next} · {runs} sent. It stops when you stop it or close LlmOnLan.',
  schedOnSkipped: 'On: next run {next} · {runs} sent · {skipped} skipped, because a reply was running. It stops when you stop it or close LlmOnLan.',
  schedNoText: 'Write the message to send first.',
  schedNoThread: 'Open a chat for this project first: the messages go into it.',
  schedBadTime: 'Choose at least {min} minutes, or a time like 08:00.',
  files: 'Files',
  noFiles: 'No files yet.',
  tabPreview: 'Preview',
  tabCode: 'Code',
  tabChanges: 'Changes',
  tabHistory: 'History',
  noHistory: 'No history yet: every reply of the agent that changes a file, and every Save, is kept here.',
  goBack: 'Go back to this version',
  latest: 'This is the current version.',
  binaryChanged: 'A binary file (a picture, a sound…) changed.',
  gitTitle: 'GitHub (or any git server over https)',
  remotePlaceholder: 'https://github.com/you/project.git',
  saveRemote: 'Save address',
  remoteSaved: 'Address saved.',
  tokenPlaceholder: 'Personal access token',
  saveToken: 'Save token',
  forgetToken: 'Forget the token',
  tokenStored: 'Token kept, encrypted by this computer.',
  tokenForgotten: 'Token forgotten.',
  tokenSaved: 'A token is kept for {host}, encrypted by this computer. It never leaves except to {host}.',
  tokenNone: 'No token for {host} yet. On GitHub: Settings ▸ Developer settings ▸ Personal access tokens ▸ Fine-grained, with "Contents: read and write" on this repository.',
  tokenUnsafe: 'This computer cannot keep a token encrypted, so it keeps none.',
  push: 'Push',
  pull: 'Pull',
  working: 'Working…',
  pushed: 'Pushed to {host}.',
  pulled: 'Pulled from {host}.',
  reload: 'Reload',
  save: 'Save',
  saved: 'Saved.',
  // The person's own edits stay in the editor: saving over the newer file is refused, never silent.
  conflict: 'This file changed since you opened it (the agent may have edited it), so it was not saved. Copy your changes, then click the file in the list to open the new version.',
  binary: 'Not a text file: the Preview shows it.',
  binaryOther: 'Not a text file, so it cannot be shown here. Open folder shows it on this computer.',
  noIndex: 'There is no {page} yet. Ask the agent to make one.',
  noChanges: 'The agent\'s last reply changed nothing.',
  newFile: 'New file: {path}',
  modelGood: '{model} is good at editing code.',
  modelWeak: '{model} is weak at editing code: it often runs out of room before it finishes. If the farm serves qwen3.8 or nemotron, pick one in the model menu at the top of the chat.',
  modelUnknown: 'Nobody has tried {model} on code edits yet: it may do well, or not.',
  notInstalled: 'The coding agent is not installed on this computer yet.',
  install: 'Install the coding agent (about 120 MB)',
  installCheck: 'Looking for the coding agent on GitHub…',
  installing: 'Downloading the coding agent… {percent}%',
  unpacking: 'Unpacking the coding agent…',
  installed: 'The coding agent is installed.',
  noApp: 'The coding agent runs in the LlmOnLan app, not here.',
  gone: 'This project\'s folder is not there any more (moved or deleted). Other project picks or makes another.',
  // LOL Vibe › Settings › About (ui/settings.mjs): what a project chat sends, beside the chat's own promise.
  aboutAgent: 'In a project chat, the coding agent also sends the files it reads to the farm\'s model. The project itself stays in its folder on this computer.',

  // Tooltips: what a control does, where its label alone does not say it. {keys} is the platform's spelling.
  tipCreate: 'Make a new project folder and tie this chat to it',
  tipPick: 'Tie this chat to this project',
  tipOther: 'Tie this chat to another project, or make a new one',
  tipFolder: 'Open the project folder on this computer',
  tipBrowser: 'Open the page in your usual web browser (on this computer only)',
  tipShare: 'Let anyone on this network open the page, read-only, until you stop sharing or close LlmOnLan',
  tipUnshare: 'Stop sharing this project on the network',
  tipKeepGoing: 'Let the agent work on a bigger job round after round until it has checked it is done, instead of one reply at a time',
  tipKeepGoingOn: 'Back to one reply per message',
  tipSchedule: 'Let the agent start by itself at set times, in this chat, while LlmOnLan is open',
  tipScheduleOn: 'See or stop the schedule',
  tipSchedStart: 'The first run is after the interval (or at the time), then again and again until you stop it or close LlmOnLan',
  tipSchedStop: 'No more runs from this schedule',
  tipTabPreview: 'The page, running: index.html, or the page or picture you picked in the list',
  tipTabCode: 'Read and edit the file you picked in the list',
  tipTabChanges: 'What the agent\'s last reply changed',
  tipTabHistory: 'Every reply that changed a file and every Save — and going back to an earlier version',
  tipReload: 'Load the page again',
  tipSave: 'Save this file ({keys}) — each Save is kept in History',
  tipGoBack: 'Make the files what they were at this version. It is a new step in History, so you can come back.',
  tipSaveRemote: 'Remember this repository address for this project',
  // One token per server (main keeps it by host): every project pushing to the same server uses it.
  tipSaveToken: 'Keep this token, encrypted by this computer, for every project on the same server. It is never shown again.',
  tipForgetToken: 'Remove the token kept for this server (every project on it)',
  tipPush: 'Send this project\'s history to the repository',
  tipPull: 'Bring newer work from the repository here (only when nothing clashes; your work is kept)',
});
