// Generate the LiteLLM proxy config.yaml from lol.config.json.
//
// The whole point: each Ollama host becomes a *deployment* of the same
// `model_name`. LiteLLM's router then load-balances across deployments that
// share a model_name and fails over when one is down — so a client asking for
// `gemma4:12b` is transparently spread across every box, and a dead box drops
// out via the cooldown. LOL never hand-edits routing; it's derived here.
//
// Refs: docs.litellm.ai (Ollama provider, routing/load-balancing, proxy config).

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

// Build the config.yaml object (model_list × hosts + router/proxy settings).
function buildLitellmConfig(config) {
    const provider = config.litellm.provider; // 'ollama_chat' | 'ollama'
    const model_list = [];
    for (const model of config.models) {
        for (const host of config.ollama.hosts) {
            model_list.push({
                model_name: model.id,                      // what clients request
                litellm_params: {
                    // ollama_chat = use Ollama's chat endpoint w/ proper templating.
                    model: `${provider}/${model.id}`,
                    api_base: host,
                },
            });
        }
    }

    const doc = {
        model_list,
        router_settings: {
            // simple-shuffle spreads load with no extra state; good default for a LAN.
            routing_strategy: 'simple-shuffle',
            // A failed call is retried on OTHER deployments of the same model, so a
            // dead host is transparently routed around. 3 retries × N deployments
            // gives a request a strong chance of landing on a healthy host.
            num_retries: 3,
            // Cool a deployment out of rotation after a SINGLE failure (fast
            // failover when a node dies — minimizes user-visible errors) …
            allowed_fails: 1,
            // … and keep it out for a minute before retrying it.
            cooldown_time: 60,
        },
        litellm_settings: {
            // Silently drop params a model doesn't support instead of erroring —
            // keeps OWUI's extra OpenAI params from breaking Ollama.
            drop_params: true,
            // Don't phone home.
            telemetry: false,
        },
        general_settings: {},
    };

    // Auth: only require a key if the operator set one. An unset key => open proxy
    // (trusted LAN). LiteLLM treats master_key as the admin/virtual key clients send.
    if (config.proxy.masterKey) {
        doc.general_settings.master_key = config.proxy.masterKey;
    }

    return doc;
}

function toYaml(doc) {
    return yaml.dump(doc, { lineWidth: 120, noRefs: true });
}

// Default on-disk location for the generated config (gitignored).
function generatedConfigPath() {
    return path.join(__dirname, '..', 'litellm', 'config.generated.yaml');
}

// Write the generated config; returns the path written.
function writeLitellmConfig(config, outPath = generatedConfigPath()) {
    const header =
        '# GENERATED by `lol` from lol.config.json — do NOT edit by hand.\n' +
        '# Re-run `lol up` to regenerate. Routing is derived, never authored.\n';
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, header + toYaml(buildLitellmConfig(config)), 'utf8');
    return outPath;
}

module.exports = { buildLitellmConfig, toYaml, generatedConfigPath, writeLitellmConfig };
