// SearXNG orchestration — ONE shared metasearch instance on the farm box, so
// every OWUI client on the LAN gets web search with zero client setup (the
// client reads `searxngUrl` from the beacon snapshot and sets OWUI's
// SEARXNG_QUERY_URL). The search FEATURE still runs client-side (each OWUI
// queries this instance and fetches/embeds result pages locally); this box only
// hosts the metasearch engine.
//
// Design (verified against docs.searxng.org + the searxng repo, then adjusted
// after live testing on Windows):
//   • Run from a source checkout with `python -m searx.webapp` (Flask threaded
//     dev server — fine for workshop scale; granian is container-only upstream).
//     Static frontend assets are pre-built in the repo — no build step.
//   • The repo has NO tags/releases → pin a COMMIT SHA. Source is obtained as a
//     GITHUB TARBALL (not a git checkout): the repo ships uwsgi/nginx templates
//     with ':' in their filenames (utils/templates/etc/…socket), which are
//     invalid on Windows/NTFS and abort ANY git checkout (verified live; sparse
//     checkout didn't dodge it either). Tar extraction with --exclude skips
//     them entirely — and drops the git prerequisite as a bonus.
//   • Own venv under .searxng/ — SearXNG `==`-pins httpx/flask/jinja2/certifi,
//     which would fight LiteLLM's constraints in the shared farm .venv.
//   • settings.yml MUST have search.formats including `json` (else OWUI gets
//     403) and a real secret_key (webapp exits on the default). limiter stays
//     false (trusted LAN; avoids the Valkey dependency entirely).
//   • Port/bind go via env at spawn (SEARXNG_PORT / SEARXNG_BIND_ADDRESS), so a
//     config port change needs no settings rewrite.
// `rm -rf farm/.searxng` is a full uninstall.

const fs = require('fs');
const path = require('path');
const http = require('http');
const crypto = require('crypto');
const { execSync, spawn } = require('child_process');
const log = require('./log');

// Master HEAD at integration time (2026-07-01), smoke-tested on the dev box.
// Bump deliberately: change this constant and re-run `lol up` — the next run
// re-fetches + reinstalls the new source automatically (no manual file deletion).
const PINNED_SHA = '0f9e30e3f9229015df8e9df2ea63a338a81b931a';
const REPO_URL = 'https://github.com/searxng/searxng';

const IS_WIN = process.platform === 'win32';
const ROOT = path.join(__dirname, '..', '.searxng');
const SRC = path.join(ROOT, 'src');
const VENV = path.join(ROOT, 'venv');
const SETTINGS = path.join(ROOT, 'settings.yml');
const SHA_FILE = path.join(ROOT, '.installed-sha'); // what's actually pip-installed
const SRC_SHA_FILE = path.join(ROOT, '.src-sha');   // what's actually extracted in src/

function venvPython() {
    return IS_WIN ? path.join(VENV, 'Scripts', 'python.exe') : path.join(VENV, 'bin', 'python');
}

function sh(cmd, opts = {}) { execSync(cmd, { stdio: 'inherit', ...opts }); }
function shCapture(cmd) {
    try { return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); }
    catch { return null; }
}

// Find a usable Python (same ladder as `lol install`'s LiteLLM venv).
function findPython() {
    const candidates = IS_WIN
        ? ['py -3.12', 'py -3.11', 'py -3', 'python', 'python3']
        : ['python3.12', 'python3.11', 'python3', 'python'];
    for (const c of candidates) {
        const v = shCapture(`${c} --version`);
        if (v && /Python 3\.(10|11|12|13)\b/.test(v)) return { cmd: c, version: v };
    }
    return null;
}

// The minimal settings.yml body. Exported for tests. Port/bind deliberately
// absent — they ride in as env at spawn time.
function buildSettingsYaml(secretKey) {
    return [
        '# Generated by `lol up` — delete this file to regenerate (new secret).',
        'use_default_settings: true',
        'general:',
        '  debug: false',
        '  instance_name: "LlmOnLan Search"',
        'server:',
        `  secret_key: "${secretKey}"`,
        '  limiter: false          # trusted LAN; avoids the Valkey requirement',
        '  public_instance: false',
        '  image_proxy: false',
        'search:',
        '  formats:                # json is REQUIRED for Open WebUI (else 403)',
        '    - html',
        '    - json',
        '',
    ].join('\n');
}

function writeSettingsIfMissing() {
    if (fs.existsSync(SETTINGS)) return;
    fs.mkdirSync(ROOT, { recursive: true });
    fs.writeFileSync(SETTINGS, buildSettingsYaml(crypto.randomBytes(32).toString('hex')), 'utf8');
    log.ok(`SearXNG settings → ${log.paint.grey(SETTINGS)}`);
}

function readTrim(p) {
    try { return fs.readFileSync(p, 'utf8').trim(); } catch { return null; }
}

// Installed AND matching the pin: the venv exists, the source is still on disk,
// and what's recorded as installed is exactly PINNED_SHA (a master-fallback stamp
// won't match, so a later run re-attempts the pin).
function installed() {
    return fs.existsSync(venvPython())
        && fs.existsSync(path.join(SRC, 'searx'))
        && readTrim(SHA_FILE) === PINNED_SHA;
}

// Download a URL to a file (redirect-following; GitHub /archive/ redirects to
// codeload). Node's global fetch keeps this dependency-free.
async function download(url, dest) {
    const res = await fetch(url, { redirect: 'follow' });
    if (!res.ok) throw new Error(`HTTP ${res.status} downloading ${url}`);
    fs.writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
}

// Windows shim (verified live): searx/valkeydb.py does a top-level `import pwd`
// (POSIX-only) that crashes the webapp on Windows — yet pwd is only used inside
// a valkey-connection-error log line, and we never configure valkey (limiter is
// false). Make the import conditional. The install is editable (-e), so patching
// the source tree is live; idempotent and a no-op once upstream fixes it.
function patchWindowsCompat() {
    if (!IS_WIN) return;
    const file = path.join(SRC, 'searx', 'valkeydb.py');
    try {
        const src = fs.readFileSync(file, 'utf8');
        if (/^import pwd$/m.test(src) && !src.includes('lol shim')) {
            fs.writeFileSync(file, src.replace(
                /^import pwd$/m,
                'try:\n    import pwd\nexcept ImportError:  # Windows (lol shim): pwd is only used in a valkey-error log line\n    pwd = None'
            ), 'utf8');
            log.ok('Patched searx/valkeydb.py for Windows (POSIX-only `import pwd`).');
        }
    } catch { /* file moved upstream — the boot health-wait will surface it */ }
}

// Idempotent setup: source tarball (pinned SHA) + venv + pip install + settings.
// Returns true when SearXNG is ready to spawn; false (with warnings) when the
// farm should come up WITHOUT websearch (missing python/tar, install failure).
async function ensureSearxng() {
    writeSettingsIfMissing();
    if (installed()) { patchWindowsCompat(); return true; }

    const py = findPython();
    if (!py) {
        log.warn('No Python 3.10–3.13 found — cannot install SearXNG (needed for its venv).');
        return false;
    }

    try {
        // What the source on disk currently is (null if none / different).
        let fetchedSha = PINNED_SHA;
        // 1. Fetch the source UNLESS an already-extracted tree matches the pin.
        //    Guard on the recorded src SHA, NOT mere existence — otherwise bumping
        //    PINNED_SHA would silently reuse the old commit's tree. Extracted
        //    WITHOUT utils/ (its colon-named files are invalid on NTFS — see header).
        if (!fs.existsSync(path.join(SRC, 'searx')) || readTrim(SRC_SHA_FILE) !== PINNED_SHA) {
            log.step(`Downloading SearXNG source @ ${PINNED_SHA.slice(0, 10)} …`);
            fs.rmSync(SRC, { recursive: true, force: true });
            fs.mkdirSync(SRC, { recursive: true });
            const tarball = path.join(ROOT, 'searxng-src.tar.gz');
            try {
                await download(`${REPO_URL}/archive/${PINNED_SHA}.tar.gz`, tarball);
            } catch (e) {
                log.warn(`Pinned-SHA tarball failed (${e.message}) — falling back to master.`);
                await download(`${REPO_URL}/archive/refs/heads/master.tar.gz`, tarball);
                fetchedSha = null; // moving master — must never satisfy the pin
            }
            sh(`tar -xzf searxng-src.tar.gz -C src --strip-components=1 --exclude "*/utils/*"`, { cwd: ROOT });
            fs.rmSync(tarball, { force: true });
            if (!fs.existsSync(path.join(SRC, 'searx'))) throw new Error('extraction produced no searx/ package');
            // Record what we actually extracted BEFORE pip, so a later pip failure
            // + re-run reuses this tree instead of re-downloading.
            fs.writeFileSync(SRC_SHA_FILE, (fetchedSha || 'master') + '\n', 'utf8');
        }
        patchWindowsCompat();

        // 2. Own venv (never the LiteLLM one — conflicting `==` pins).
        if (!fs.existsSync(venvPython())) {
            log.step(`Creating SearXNG venv with ${log.paint.bold(py.version)} …`);
            sh(`${py.cmd} -m venv "${VENV}"`);
        }

        // 3. Install. Runtime deps MUST land first: setup.py imports searx/,
        //    which imports msgspec at build-metadata time — so the editable
        //    install (per docs.searxng.org: PEP 517, no build isolation) only
        //    works against a venv that already has requirements.txt installed.
        const vpy = venvPython();
        log.step('Installing SearXNG into its venv (a minute or two) …');
        sh(`"${vpy}" -m pip install -q -U pip setuptools wheel pyyaml`);
        sh(`"${vpy}" -m pip install -q -r "${path.join(SRC, 'requirements.txt')}"`);
        try {
            sh(`"${vpy}" -m pip install -q --use-pep517 --no-build-isolation -e "${SRC}"`, { cwd: SRC });
        } catch {
            // Editable installs can be fragile (paths with spaces) — plain install
            // works too: setup.py package_data ships settings/static/templates.
            log.warn('Editable install failed — retrying as a regular install.');
            sh(`"${vpy}" -m pip install -q --use-pep517 --no-build-isolation "${SRC}"`, { cwd: SRC });
        }

        // Stamp what's ACTUALLY installed — the extracted source's SHA, not the pin
        // unconditionally. A master fallback records 'master', which installed()
        // won't accept, so a later `lol up` re-attempts the pin instead of falsely
        // reporting it satisfied.
        fs.writeFileSync(SHA_FILE, (readTrim(SRC_SHA_FILE) || 'master') + '\n', 'utf8');
        log.ok(`SearXNG installed → ${log.paint.grey(ROOT)}`);
        return true;
    } catch (e) {
        log.warn(`SearXNG install failed (${e.message}) — the farm will run WITHOUT web search.`);
        log.info(`  Retry: delete ${ROOT} and re-run \`lol up\`.`);
        return false;
    }
}

// Spawn the instance: <venv python> -m searx.webapp, bound to the LAN.
function spawnSearxng(config) {
    const child = spawn(venvPython(), ['-m', 'searx.webapp'], {
        cwd: SRC,
        windowsHide: true,
        detached: !IS_WIN,
        env: {
            ...process.env,
            SEARXNG_SETTINGS_PATH: SETTINGS,
            SEARXNG_BIND_ADDRESS: '0.0.0.0',
            SEARXNG_PORT: String(config.websearch.port),
            // Same cp1252 crash-guard as the LiteLLM spawn (Windows consoles).
            PYTHONUTF8: '1',
            PYTHONIOENCODING: 'utf-8',
        },
        stdio: ['ignore', 'pipe', 'pipe'],
    });
    return child;
}

function get(url, timeoutMs = 3000) {
    return new Promise((resolve) => {
        const req = http.get(url, { timeout: timeoutMs }, (res) => {
            res.resume();
            res.on('end', () => resolve(res.statusCode));
        });
        req.on('timeout', () => req.destroy());
        req.on('error', () => resolve(null));
    });
}

// Wait for /healthz, then prove the JSON format is on (the OWUI 403 gotcha).
// Returns { up, jsonOk }.
async function waitForSearxng(port, timeoutMs = 60000) {
    const t0 = Date.now();
    while (Date.now() - t0 < timeoutMs) {
        if ((await get(`http://127.0.0.1:${port}/healthz`)) === 200) {
            const jsonStatus = await get(`http://127.0.0.1:${port}/search?q=searxng&format=json`, 10000);
            return { up: true, jsonOk: jsonStatus === 200 };
        }
        await new Promise((r) => setTimeout(r, 1000));
    }
    return { up: false, jsonOk: false };
}

// Single quick liveness probe (for the farm's health timer) — did /healthz answer?
async function searxngAlive(port) {
    return (await get(`http://127.0.0.1:${port}/healthz`)) === 200;
}

module.exports = { ensureSearxng, spawnSearxng, waitForSearxng, searxngAlive, buildSettingsYaml, PINNED_SHA };
